---
# Grafana data source provisioning
"apiVersion": 1

"datasources":
  - "name": "Prometheus"
    "type": "prometheus"
    "uid": "DS_PROMETHEUS"
    "access": "proxy"
    "url": "http://prometheus:9090"
    "isDefault": true
    "editable": true
    "jsonData":
      "timeInterval": "10s"
